# Generated by Django 3.2.8 on 2021-10-14 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='status',
            field=models.CharField(default='NEW', max_length=50),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(default='NEW', max_length=50),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_date', models.DateTimeField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='chats.chat')),
            ],
        ),
    ]
